#:schema ./schema/mesoformer2.schema.json

name = "mesoformer"
description = "mesoformer"
# =============================================================================
# 
# =============================================================================
[[datasets]]
name = "urma2p5"
description = "Unrestricted Mesoscale Analysis (URMA) 2.5km CONUS"
source = "NOAA Real-Time Mesoscale Analysis (RTMA) / Unrestricted Mesoscale Analysis (URMA) was accessed on DATE from https://registry.opendata.aws/noaa-rtma."
module = "mesoformer.datasets.urma"
start_date = 2021-06-04T00:00:00Z
end_date = 2021-06-04T00:00:00Z
references = [
    "https://www.emc.ncep.noaa.gov/emc/pages/numerical_forecast_systems/rtma.php",
    "https://graphical.weather.gov/docs/ndfdSRS.htm",
]
[[datasets.channels]]
description = ""
grib_id = 228164
short_name = "tcc"
long_name = "total_cloud_cover"
type_of_level = "atmosphereSingleLayer"
level = 0
units = "%"

[[datasets.channels]]
description = ""
grib_id = 260109
short_name = "ceil"
long_name = "ceiling"
type_of_level = "cloudCeiling"
level = 0
units = "m"

[[datasets.channels]]
description = ""
grib_id = 165
short_name = "u10"

long_name = "u_wind_component_10m"
type_of_level = "heightAboveGround"
level = 10
units = "m s**-1"

[[datasets.channels]]
description = ""
grib_id = 166
short_name = "v10"
long_name = "v_wind_component_10m"
type_of_level = "heightAboveGround"
level = 10
units = "m s**-1"

[[datasets.channels]]
description = ""
grib_id = 207
short_name = "si10"
long_name = "wind_speed_10m"
type_of_level = "heightAboveGround"
level = 10
units = "m s**-1"

[[datasets.channels]]
description = ""
grib_id = 260065
short_name = "gust"
long_name = "wind_speed_gust"
type_of_level = "heightAboveGround"
level = 0
units = "m s**-1"

[[datasets.channels]]
description = ""
grib_id = 260260
short_name = "wdir10"
long_name = "wind_direction_10m"
type_of_level = "heightAboveGround"
level = 10
units = "Degree true"

[[datasets.channels]]
description = ""
grib_id = 167
short_name = "t2m"
long_name = "temperature_2m"
type_of_level = "heightAboveGround"
level = 2
units = "K"

[[datasets.channels]]
description = ""
grib_id = 168
short_name = "d2m"
long_name = "dewpoint_temperature_2m"
type_of_level = "heightAboveGround"
level = 2
units = "K"

[[datasets.channels]]
description = ""
grib_id = 174096
short_name = "sh2"
long_name = "specific_humidity_2m"
type_of_level = "heightAboveGround"
level = 2
units = "kg kg**-1"

[[datasets.channels]]
description = ""
grib_id = 134
short_name = "sp"
long_name = "surface_pressure"
type_of_level = "surface"
level = 0
units = "Pa"

[[datasets.channels]]
description = ""
grib_id = 3020
short_name = "vis"
long_name = "visibility"
type_of_level = "surface"
level = 0
units = "m"

[[datasets.channels]]
description = ""
grib_id = 228002
short_name = "orog"
long_name = "orography"
type_of_level = "surface"
level = 0
units = "m"


[datasets.crs]
geographic_crs_name = "NDFD CONUS 2.5km Lambert Conformal Conic"
projected_crs_name = "NDFD"
grid_mapping_name = "lambert_conformal_conic"
semi_major_axis = 6378137.0
semi_minor_axis = 6356752.31424518
inverse_flattening = 298.25722356301
reference_ellipsoid_name = "WGS 84"
longitude_of_prime_meridian = 0.0
prime_meridian_name = "Greenwich"
horizontal_datum_name = "WGS84"
latitude_of_projection_origin = 20.191999
longitude_of_projection_origin = 238.445999
standard_parallel = 25
false_easting = 0.0
false_northing = 0.0
units = "m"

# =============================================================================
# 
# =============================================================================
[[datasets]]
name = "era5"
description = ""
source = ""
module = ""
start_date = 2021-06-04T00:00:00Z
end_date = 2021-06-04T00:00:00Z
references = []

[[datasets.channels]]
long_name = "blah"
short_name = "unknown"
description = ""
units = "m s**-1"
# short_name = "10u"
type_of_level = "heightAboveGround"
level = 10


[datasets.crs]
geographic_crs_name = "NDFD CONUS 2.5km Lambert Conformal Conic"
projected_crs_name = "NDFD"
grid_mapping_name = "lambert_conformal_conic"
semi_major_axis = 6378137.0
semi_minor_axis = 6356752.31424518
inverse_flattening = 298.25722356301
reference_ellipsoid_name = "WGS 84"
longitude_of_prime_meridian = 0.0
prime_meridian_name = "Greenwich"
horizontal_datum_name = "WGS84"
latitude_of_projection_origin = 20.191999
longitude_of_projection_origin = 238.445999
standard_parallel = 25
false_easting = 0.0
false_northing = 0.0
units = "m"
